name:                haskell-reps
version:             0.1.0.0
github:              "flipstone/rep-library"
license:             BSD3
author:              "Flipstone Technology Partners"
maintainer:          "david@flipstone.com"
copyright:           "2020 Flipstone Technology Partners"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-reps#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- free

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: haskell

